# Permalinks
permalink:        pretty

# Setup
title:            Hyde
tagline:          A Jekyll theme
description:      A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.
url:              "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl:          "" # the subpath of your site

author:
  name:           Mark Otto
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

# Build settings
markdown:         kramdown
highlighter:      rouge
theme:            hyde-theme
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
