# Dependencies
# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
css_class: 'highlight'

# Permalinks
permalink:        pretty


# Setup
title:              Valentina Carraro
tagline:            Digital Geographies & Controversies
excerpt_separator:  <!--stop-->

# URLs
url:              http://hyde.getpoole.com
baseurl:          /

# Site identity

author:
  name:           Valentina Carraro
  url:            https://twitter.com/valecrrr

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ralentina.github.io
