# Permalinks
permalink:        pretty

# Setup
title:            Ada & Co
tagline:          'Fun Stuff'
description:      'Cool stuff for cool people'
url:              http://www.kea.zone
baseurl:          /

author:
  name:           'Matt Corich'
  url:            https://www.linkedin.com/in/mattcorich/

paginate:         5
