# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            fhcrc.io
tagline:          '<i>Education</i> and <i>access to</i> computational methods at the <a href="http://fhcrc.org" target="_blank">Fred Hutchinson Cancer Research Center</a>.'
description:      '<i>Education</i> and <i>access to</i> computational methods at the <a href="http://fhcrc.org" target="_blank">Fred Hutchinson Cancer Research Center</a>.'
url:              http://fhcrc.io

paginate:         5

# Custom vars

github:
  repo:           https://github.com/fhcrcio/fhcrc.io

trello:           https://trello.com/b/IwMlMEWl/fhcrc-io
