# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Ellesa Sabasaje
tagline:          'The Magnificent Miscellany of Ellesa Sabasaje'
description:      'The Personal Disquiet of Ellesa Sabasaje'
url:              http://ellesa.me
baseurl:          /

author:
  name:           'Ellesa Sabasaje'
  url:            https://twitter.com/ezakaze

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           
