# Dependencies
imarkdown:        redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Sunny's Tech Note
tagline:          ''
description:      'Life is a marathon not a sprint.'
url:              https://www.ssjlin9999.com
baseurl:          /

author:
  name:           'Sunny Lin'
  url:            

paginate:         5

# Custom vars
version:          0.1.0

gems:		          [jekyll-paginate]
plugins: 	        [jekyll-paginate]

github:
  repo:           https://github.com/ssjlin9999/ssjlin9999
