# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Adel Lahlou
tagline:          "Adel's site about a developer, budding data scientist, witty jokes, and occasionally food."
description:      "Adel's site about a developer, budding data scientist, witty jokes, and occasionally food."
url:              http://adellahlou.com
baseurl:          /

author:
  name:           'Adel Lahlou'
  url:            https://github.com/adellahlou

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/adellahlou
