# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Furkan Mısır
tagline:          'Furkan Mısır'ın bloğu'
description:      'Yazmaya değer bulduğum teknoli,kültür,sanat ve bilim gibi konuların olduğu blog. '
url:              https://misirfurkan.github.io/
baseurl:          https://misirfurkan.github.io/


author:
  name:           'Furkan Mısır'
  url:            https://instagram.com/misirfurkanz

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
