# Dependencies
markdown:         kramdown
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
css_class: 'highlight'
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Valentina Carraro
tagline:          Digital Geographies & Controversies
description:      HK-RGC PhD Fellow, City University of Hong Kong
url:              https://ralentina.github.io/
baseurl:          /

author:
  name:           Valentina Carraro
  url:            https://twitter.com/valecrrr

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ralentina.github.io
