# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Purview
tagline:          'Some unscathing words'
description:      'A brazen column'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Prateek Bagri'
  url:            https://twitter.com/prateekbagri

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
