#
# This file contains configuration flags to customize your site
#
markdown: kramdown

# Name of your site (displayed in the header)
name: Ron Apelbaum

# Short bio or description (displayed in the header)
description: I blog about front end
