# Permalinks
permalink:        pretty

# Setup
title:            Ada & Co
tagline:          'Lead Developer'
description:      'fill in some stuff here'
url:              http://www.kea.zone
baseurl:          /

author:
  name:           'Matt Corich'
  url:            https://www.linkedin.com/in/mattcorich/

paginate:         5
