# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
#permalink:        pretty


# Setup
title:            Divyanka
tagline:          'Student'
description:      'Hi, I'm Divyanka. I'm a Computere Science Sophomore at IIT Delhi and this is my personal website. Made by <a href="https://github.com/divyankachaudhari" target="_blank">@divyankachaudhari</a>.'
url:              https://divyankachaudhari.github.io/
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
