# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Purview
tagline:          'Some Unscathing Words'
description:      'A brazen column'
url:              https://prateekbagri.github.io/
baseurl:          /

author:
  name:           'Prateek Bagri'
  url:            https://twitter.com/prateekbagri

paginate:         5

