# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'musings of a starseed'
tagline:          'eye've always been naked'
description:      'What would be commonly referred to as a journal.'
url:              http://musingsofastarseed.tk
baseurl:          /

author:
  name:           'STARSEED'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
