# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Shahin Khobahi
tagline:          'My Inner Café'
description:      'My Inner Café'
url:              
baseurl:          /

author:
  name:           'Shahin Khobahi'
  url:            https://skhobahi.github.com

paginate:         5

# Custom vars
version:          

github:
  repo:           
