# Setup
title:            The Beekeeper
tagline:          'A Jekyll theme'
description:      'Information for The Beekeeper by a beekeeper.'
# use to add a link to the description.   ' <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://dpepoon.github.io
baseurl:          /TheBeekeeper
paginate:         5

# About and contact
author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# git hub
github:
  repo: https://github.com/dpepoon/TheBeekeeper
   
# Custom vars
version:          3.0.0

collections:
  glossary:
    output: true
