# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Smartling'
tagline:          'Developer Documentation'
description:      'Here you'll find everything you need to integrate Smartling into your development process, whether you're using files or Smartling's GDN. For help with the Smartling Dashboard, see our <a href="http://support.smartling.com" target="_blank">Help Center</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Smartling'
  url:            http://www.smartling.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
