# Dependencies
markdown:         redcarpet
highlighter:      pygments
gems:			  [jekyll-paginate, jekyll-gist]

# Permalinks
permalink:        pretty

# Setup
title:            Rohit Ravikoti
tagline:          'Simplifying the complex'
description:      ''
url:              http://rohitravikoti.xyz
baseurl:          ""

author:
  name:           'Rohit Ravikoti'
  url:            https://twitter.com/rohitravikoti

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rravikot/rravikot.github.io/

sass:
    sass_dir: 	  public/_scss