# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Divyanka Chaudhari
tagline:          'Undergraduate'
description:      'I'm a Computer Science & Engineering sophomore at IIT Delhi. This is my personal website.'
url:              https://iceberry25.github.io/
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          0.1.1

github:
  repo:           https://github.com/Iceberry25/
