# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Liuuu
tagline:          'A Jekyll theme'
description:      'A  simple site '
url:              
baseurl:          https://github.com/liuuu/liuuu.github.io/

author:
  name:           'Liuuu'
  url:            https://twitter.com/newliuuu

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
