# Permalinks
permalink:        pretty

# Setup
title:            HITO
tagline:          'A Health IT Ontology'
description:      'A Health IT Ontology for systematically describing application systems and software products in health IT. By <a href="" target="_blank">IMISE</a> and <a href="" target="_blank">UMIT</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Konrad Höffner'
  url:            https://github.com/KonradHoeffner

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/hito/hitontology

plugins:
  - jekyll-paginate
  - jekyll-gist
