# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            fhcrc.io
tagline:          'Supporting the computational community at the <a href="http://fhcrc.org" target="_blank">FHCRC</a>'
description:      'An organizing center for computational education and development at the FHCRC.'
url:              http://fhcrc.io

paginate:         5

# Custom vars

github:
  repo:           https://github.com/poole/hyde
