# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
#permalink:        pretty


# Setup
title:            Divyanka
tagline:          'Student'
description:      'Hi, I am Divyanka Chaudhari. I am a Computer Science Sophomore at <a href="https://www.cse.iitd.ernet.in/" target="_blank">IIT Delhi</a> and this is my personal website.'
url:              https://divyankachaudhari.github.io/
baseurl:          /

author:
  name:           'Divyanka Chaudhari'
  url:            https://divyankachaudhari.github.io/

paginate:         5

# Custom vars
# version:          2.1.0

github:
  repo:           https://github.com/divyankachaudhari
