# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            universal yapping property
tagline:          'uyp - math/cs-related things'
description:      'A personal blog for recording (proof, code)writing progress. Theme Hyde made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://utkuboduroglu.github.io
baseurl:          /

author:
  name:           'Utku Boduroğlu'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
