# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            <img src="MyBeautifulFace.png" alt="cosmin" style="width:304px;height:228px;">
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://cosmin1123.github.io
baseurl:          /

author:
  name:           'Theodor-Cosmin Didii'
  url:            https://www.facebook.com/cosmin.didii

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/cosmin1123/cosmin1123.github.io
