# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Matt Corich
tagline:          'Lead Developer'
description:      'fillin some stuff here'
url:              http://kea.zone
baseurl:          /

author:
  name:           'Matt Corich'
  url:            https://www.linkedin.com/in/mattcorich/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/korich
