# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Testio Tech
tagline:          'A blog related to software testing'
description:      'This is my personal blog related to software testing, and will include practical posts on test tools/methodlogies, test startegies and wider topics.'
url:              https://dp2020-dev.github.io
baseurl:          

author:
  name:           'Daniel Phillips'
  url:            www.linkedin.com/in/daniel-phillips-ba99161b8

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:          https://github.com/dp2020-dev/dp2020-dev.github.io
