# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            I Love Computers!
tagline:          'Tutorials, fun Projects, How-to, and More!'
description:      'Online Resource for learning how to make working with computers more fun and interesting. Topics Include Home automation, Network Administration, Automate Tasks with Scripts, and General Operating System Hacks.'
url:              html://glenlarkin.github.io
baseurl:          /blog

author:
  name:           'Glen Larkin'
  url:            https://glenlarkin.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
