# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            fhcrc.io
tagline:          'Computational community at the <a href="http://fhcrc.org" target="_blank">Fred Hutchinson Cancer Research Center</a>.'
description:      'Computational community at the <a href="http://fhcrc.org" target="_blank">Fred Hutchinson Cancer Research Center</a>.'
url:              http://fhcrc.io

paginate:         5

# Custom vars

github:
  repo:           https://github.com/fhcrcio/fhcrc.io
