# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            light life
tagline:          'Conscious, balanced, and light living'
description:      'Guides on a present, light, and balanced life'
url:              http://livinglightly.tk
baseurl:          /

author:
  name:           'A. Being'
  url:            livinglightly.tk

paginate:         5
