# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            LIVING LIGHTLY
tagline:          'Conscious, balanced, and light living'
description:      'A blog dedicated to a light and present experience of being'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'A. Being'
  url:            

paginate:         5

