# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Ciarán
tagline:          'UX & Front End'
description:      'Blog & Portfolio'
url:              http://ciaranhanrahan.com
baseurl:          /

author:
  name:           'Ciarán Hanrahan'
  url:            https://twitter.com/ciaranhan

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/Jaibles/jaibles.github.io
