# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Practice Web Development
tagline:          'Practice HTML, CSS and Javascript'
description:      'Practice HTML, CSS and Javascript'
url:              https://devpractical.com
baseurl:          /

author:
  name:           'Avic Ndugu'
  url:            https://twitter.com/avic-ndugu

paginate:         5
paginate_path:    "blog/page:num/"

# Custom vars
# version:          2.1.0

# github:
  # repo:           https://github.com/poole/hyde

plugins:
  - jekyll-paginate
  - jekyll-gist
  - kramdown