# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Testio Tech
tagline:          'A blog related to software testing'
description:      'This is my personal blog related to software testing, and will include practical posts on test tools/methodlogies, test startegies and wider topics.'
url:              https://dp2020-dev.github.io
baseurl:          /

author:
  name:           'Daniel Phillips'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://dp2020-dev.github.io
