# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            To be Done
tagline:          'A Jekyll theme'
description:      <img src="MyBeautifulFace.png" alt="cosmin" style="width:120px;height:120px;border-radius:120px;margin-left:auto;margin-right:auto;">
url:              http://cosmin1123.github.io
baseurl:          /

author:
  name:           'Theodor-Cosmin Didii'
  url:            https://www.facebook.com/cosmin.didii

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/cosmin1123/cosmin1123.github.io
