# Dependencies
markdown:         redcarpet
highlighter:      pygments

encoding:         UTF-8

# Permalinks
permalink:        pretty
relative_permalinks: true

# Gems
gems:
- jekyll-redirect-from

# Setup
title:            tinypalace
tagline:          'games festival'
description:      '(╯°□°）╯︵ ┻━┻'
url:              http://tinypalace.de
baseurl:

author:
  name:           'tiny'
  url:            https://twitter.com/tinypalace_
  email:          tinypalace@posteo.de

paginate:         8

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/tinypalace/tinypalace.github.io

defaults:
  -
    scope:
      path: "_posts/en"
    values:
      lang: en
      layout: default
  -
    scope:
      path: _posts/de
    values:
      lang: de
