# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            living lightly
tagline:          'Conscious, balanced, and light living'
description:      'Writings on light, truth, and the present experience of being'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'A. Being'
  url:            

paginate:         5

