# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Gaea Project
tagline:          'per Eric Parga'
description:      'Compendi de l&#39;univers literari d&#39;Eric Parga.'
url:              http://hacknug.github.io/
baseurl:          /

author:
  name:           'Nestor Vera'
  url:            https://twitter.com/hack_nug

paginate:         2

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

collections:
  characters:
    output:       true
