# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            frontend.io
tagline:          'A Jekyll theme'
description:      'I blog about front end'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Ron Apelbaum'
  url:            https://github.com/ronapelbaum

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ronapelbaum
