# Setup
title:            'Cloud Blog'
tagline:          'A Blog on Cloud,Deployment and Devops'
description:      'Everything I have experienced and experimented on cloud and Deployments - <a href="https://twitter.com/ajo.mathew">@ajo.mathew</a>"'
url:              https://blog.ajomathew.dev
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Ajo Mathew'
  url:            https://twitter.com/ajo.mathew

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
