# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Jacob DeCourcey
tagline:          'A front-end web developer in Culpeper, VA'
description:      "A blog to keep track progress on my 2018 learning goals."
url:              https://www.linkedin.com/in/jacobdecourcey
baseurl:          /

author:
  name:           'Jacob DeCourcey'
  url:

paginate:         5

# Custom vars
version:          2.1.0

github:           https://github.com/jakedecourcey
