# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Suramrit Singh 
tagline:          'Portfolio'
description:      'A software engineer with an inclination for distributed systems and application infrastructure'
url:              https://suramrit.github.io/about-me/
baseurl:          /

author:
  name:           'Suramrit Singh'
  url:            https://twitter.com/suramrit

paginate:         1

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/suramrit/about-me
