# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            frontend.io
tagline:          ronapelbaum
description:      'I blog about front end'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Ron Apelbaum'
  url:            https://github.com/ronapelbaum

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ronapelbaum

links:
  email: ronapelbaum@gmail.com
  rss:
  github: ronapelbaum
  linkedin: ronapelbaum
  stackoverflow: ronapelbaum
  facebook:
  googleplus:
  youtube: